### ISSUE TITLE
Game seems to ignore speed up and speed down options

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2450] opened 2016-08-29 11:14 UTC
Clicking + or - doesn't change game speed. Holding doesn't work also.

**Comment by MasterofJOKers** [comment] 2016-08-29 11:15
Does the Number next to + and - change?

**Comment by CrafterSvK** [comment] 2016-08-29 11:17
No. But after rebinding to M & N works just fine. Even badly it should have limit.

**Comment by MasterofJOKers** [comment] 2016-08-29 11:19
So you meant using the + and - keys, doesn't work, not the GUI buttons?

What do you think the limit should be? My old laptop can hardly handle 2x while my newer laptop can handle ~8x and my desktop should be able to handle even more.

**Comment by MasterofJOKers** [comment] 2016-08-29 11:20
Does + and - work, if you re-bind the functionality to these keys? Did you use +/- from the numpad?

**Comment by CrafterSvK** [comment] 2016-08-29 11:21
The people are teleporting on 6x speed on my desktop. i3, GTX 650, 8Gb RAM ArchLinux. I used +/- on numpad and in options it was detected. I have no other +/- on my keyboard.

**Comment by jorgesumle** [comment] 2016-08-29 11:24
Maybe you have number keypad blocked. Is Num Lock on?

**Comment by LinuxDonald** [comment] 2016-08-29 11:24
I think Max should be 8x or 11x

**Comment by MasterofJOKers** [comment] 2016-08-29 11:25
Numpad +/- are not necessarily the same +/- as others - even if you don't have other +/-.

**Comment by CrafterSvK** [comment] 2016-08-29 11:26
Yes it is. I tried with off and it doesn't work anyway. Yeah 8x is okay. More than it should freeze a lot of PCs. I have binded with them so it should work.

**Comment by MasterofJOKers** [comment] 2016-08-29 19:31
Btw. the current upper bound is 20x.

**Comment by MasterofJOKers** [comment] 2016-08-29 19:37
Confirmed, that numpad +/- does not work like the other +/-, as they send different keycodes.

Regardingt he cap of speed: I'm against capping the speed, as a human should be able to tell, if its PC is capable of running at this speed or not. Having a hard cap is imho bad, because it is only correct for a small number of PCs.

**Comment by CrafterSvK** [comment] 2016-08-29 20:01
Why is max cap good. Rapidly tap + for max speed. Don't need to count how many times you want. If you don't want to do that don't do that. But better to do it in options. So you can select uncapped and cap at 8 16 32 and so on.

**Comment by MasterofJOKers** [comment] 2016-08-29 20:02
Option sound better since "max speed" is different per PC as I already said.

**Comment by CrafterSvK** [comment] 2016-08-29 20:03
Yeah as I just think of it. :)

**Comment by jmdejong** [comment] 2018-04-24 18:44
Setting the numpad keys to change the speed is to too hard (just add `KP_PLUS` and `KP_MINUS` to the keys settings)

However, if this would be set it could not be unset from the settings menu.
There are already 2 keybindings used for speed up, and only 2 bindings are displayed in the menu.
Furthermore, the code trying to detect what key you pressed for the settings incorrectly thinks that they numpad plus is `PLUS` instead of `KP_PLUS` (same for minus).

I could change it so that the numpad plus and minus key can be used, but to rebind it users will have to manually edit settings.xml

Is this a problem?

**Comment by jmdejong** [comment] 2018-05-16 19:59
The original problem has been fixed with #2834.
Should we close this or keep it open for the 'max speed' setting?

**Comment by AndyMender** [comment] 2018-05-16 20:03
Up to @LinuxDonald I think.

The only thing I would say is that keybindings and the actual game effect are two different things. Game speed can be changed manually without relying on specific keyboard key presses.

**Comment by jmdejong** [comment] 2018-05-16 20:06
I thought that the original problem was that the expected keypresses did not correct the game speed?

**Comment by AndyMender** [comment] 2018-05-16 20:08
Yes, correct!

**Closed** 2018-05-16 22:01 UTC
