### ISSUE TITLE
Ship is displayed on coast on rotated view

### ISSUE THREAD

**Issue by totycro** [unknown-horizons/unknown-horizons#796] opened 2011-11-04 02:20 UTC
Those two screenshots show a ship at the same position, but with a rotated view:

default view rotation:
http://img717.imageshack.us/f/76260689.png/

rotated by 180:
http://img5.imageshack.us/f/86295464.png/

It seems as if the ship is acctually drawn a few pixels "above" the acctual position, which makes it look as if the ship is on the island.

[> Link to originally reported Trac ticket <] (http://trac.unknown-horizons.org/t/ticket/796)
**Attachment**: [ship rotated view display error.sqlite](http://up.unknown-horizons.org/f/?id=157&n=ship+rotated+view+display+error.sqlite)

**Comment by squiddy** [comment] 2016-10-25 21:31
Most likely a duplicate of #1379

**Closed by squiddy** 2016-10-25 21:31 UTC
Labels: B-bug
