### ISSUE TITLE
Free Play not working

### ISSUE THREAD

**Issue by iganev** [unknown-horizons/unknown-horizons#2319] opened 2015-02-25 20:39 UTC
Latest release on openSUSE. When I click "Free Play" the game crashes and here's the trace:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(*args,**kwargs)
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/events.py", line 164, in delayed_f
    f( event )
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/events.py", line 327, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable
    return func(*args,**kwargs)
  File "/usr/lib/python2.7/site-packages/horizons/util/python/callback.py", line 47, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/horizons/gui/modules/singleplayermenu.py", line 98, in _select_mode
    self._mode.show()
  File "/usr/lib/python2.7/site-packages/horizons/gui/modules/singleplayermenu.py", line 399, in show
    self._update_map_infos()
  File "/usr/lib/python2.7/site-packages/horizons/gui/modules/singleplayermenu.py", line 408, in _update_map_infos
    number_of_players = SavegameManager.get_recommended_number_of_players(map_file)
  File "/usr/lib/python2.7/site-packages/horizons/savegamemanager.py", line 218, in get_recommended_number_of_players
    ("SELECT value FROM properties WHERE name = ?", "players_recommended")
  File "/usr/lib/python2.7/site-packages/horizons/util/dbreader.py", line 48, in __call__
    self.cur.execute(command, args)
OperationalError: no such table: properties

**Comment by stubb** [comment] 2015-02-25 20:52
@iganev Do you have some selfmade maps in your local unknown horizons folder? Seems like there is one map which can't be loaded. https://github.com/unknown-horizons/unknown-horizons/wiki/FAQ#savegames There's another folder called maps in the same folder as the save folder.

**Comment by iganev** [comment] 2015-02-25 22:34
Nope. Brand new installation, just finished the tutorial.

I have found another bug (the game crashed out of no where after 2 hours of play) but I didnt record the output, will save it if it happens again.

Great game nonetheless :)

**Comment by iganev** [comment] 2015-02-25 22:36
And by the way... I dont know about selfmade maps, but it seems that a certain db table is missing in the database.

**Comment by stubb** [comment] 2015-02-25 22:42
can you replace the __call__ function in the file horizons/util/dbreader.py with the following code and try again?
```
	@decorators.make_constants()
	def __call__(self, command, *args):
		"""Executes a sql command.
		@param command: str containing the raw sql command, with ? as placeholders for values (eg. SELECT ? FROM ?). command must not end with ';', it's added automatically here.
		@param args: tuple containing the values to add into the command.
		"""
		assert not command.endswith(";")
		command = '%s;' % command
		result = None
		try:
			self.cur.execute(command, args)
			result = self.cur.fetchall()
		except sqlite3.OperationalError as err:
			print('Warning: Cannot read {file}: {exception}'.format(file=self.db_path, exception=err))
		return result	
```
The main problem is, I am not able to reproduce your problem.

**Comment by gryffus** [comment] 2015-04-01 01:35
Since i am able to reproduce the issue, here is requested backtrace with suggested change:

```pytb
Warning: Cannot read content/maps/Archland-custom.sqlite: no such table: properties
Warning: Cannot read /tmp/tmpR35UFs: no such table: ground
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(*args,**kwargs)
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/events.py", line 164, in delayed_f
    f( event )
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/events.py", line 327, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable
    return func(*args,**kwargs)
  File "/usr/lib/python2.7/site-packages/horizons/util/python/callback.py", line 47, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/horizons/gui/modules/singleplayermenu.py", line 98, in _select_mode
    self._mode.show()
  File "/usr/lib/python2.7/site-packages/horizons/gui/modules/singleplayermenu.py", line 399, in show
    self._update_map_infos()
  File "/usr/lib/python2.7/site-packages/horizons/gui/modules/singleplayermenu.py", line 412, in _update_map_infos
    self._update_map_preview(map_file)
  File "/usr/lib/python2.7/site-packages/horizons/gui/modules/singleplayermenu.py", line 424, in _update_map_preview
    world = load_raw_world(map_file)
  File "/usr/lib/python2.7/site-packages/horizons/world/__init__.py", line 744, in load_raw_world
    world.load_raw_map(SavegameAccessor(map_file, True), preview=True)
  File "/usr/lib/python2.7/site-packages/horizons/world/__init__.py", line 267, in load_raw_map
    for (islandid,) in savegame_db("SELECT DISTINCT island_id + 1001 FROM ground"):
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "/usr/bin/unknown-horizons", line 380, in <module>
    main()
  File "/usr/bin/unknown-horizons", line 189, in main
    ret = horizons.main.start(options)
  File "/usr/lib/python2.7/site-packages/horizons/main.py", line 281, in start
    horizons.globals.fife.run()
  File "/usr/lib/python2.7/site-packages/horizons/engine/engine.py", line 276, in run
    self.loop()
  File "/usr/lib/python2.7/site-packages/horizons/engine/engine.py", line 283, in loop
    self.engine.pump()
  File "/usr/lib64/python2.7/site-packages/fife/fife.py", line 2167, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by gryffus** [comment] 2015-04-01 02:40
This is a packaging bug. I have checked the file content/maps/Archland-custom.sqlite and it is empty. After deletion, the error disappears. The file should not even be there. I really don't know how it get there and what source tarball is that. In the official https://github.com/unknown-horizons/unknown-horizons/releases/download/2014.1/unknown-horizons-2014.1.tar.xz there is no such file - @manuelm ?
Anyway I refreshed package sources of openSUSE and Fedora packages on Open Build Service with the official release (you can track the SR here: https://build.opensuse.org/request/show/293868), so lets just wait for rebuild and it should be OK. Just look in your /usr/share/unknown-horizons/content/maps folder and delete Archland-custom.sqlite if it's there and if you are having this problem.

I still think that there should be some exception handling when loading saved maps and if some cannot be loaded, show user some warning window and let him delete it.

**Comment by gryffus** [comment] 2015-04-01 03:55
I have checked other source files and they do not contain the broken Archland-custom map. Namely: https://github.com/unknown-horizons/unknown-horizons/archive/2014.1.zip and https://github.com/unknown-horizons/unknown-horizons/archive/2014.1.tar.gz
So only broken is https://github.com/unknown-horizons/unknown-horizons/releases/download/2014.1/unknown-horizons-2014.1.tar.xz .

**Comment by manuelm** [comment] 2015-04-01 11:21
@gryffus SR is accepted. Thanks for looking into this.
@iganev Can you retest with unknown-horizons-2014.1-5.1.uh please? Should be available in a few minutes.

**Comment by gryffus** [comment] 2015-04-01 11:29
@manuelm Sorry for little OT, but could you please accept https://build.opensuse.org/request/show/290829 ? Thx

**Comment by stubb** [comment] 2015-04-12 12:50
content/maps/Archland-custom.sqlite isn't part of the git repository. So iam going to close this. Seems like everything is fine now.

**Closed by stubb** 2015-04-12 12:50 UTC
Labels: bad usability, bug, crash
