### ISSUE TITLE
Trade route warning

### ISSUE THREAD

**Issue by otinn** [unknown-horizons/unknown-horizons#1695] opened 2012-04-10 08:02 UTC
Some route config interaction produces this warning:

``` pytb
Traceback (most recent call last):
  File "run_uh.py", line 547, in <module>
    main()
  File "run_uh.py", line 275, in main
    profile.runctx('horizons.main.start(options)', globals(), locals(), outfilename)
  File "D:\Tools\Python27\lib\cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "D:\Tools\Python27\lib\cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "D:\UnknownHorizons\unknown-horizons\horizons\main.py", line 247, in start
    fife.run()
  File "D:\UnknownHorizons\unknown-horizons\horizons\engine\engine.py", line 244, in run
    self.loop()
  File "D:\UnknownHorizons\unknown-horizons\horizons\engine\engine.py", line 253, in loop
    self.engine.pump()
  File "D:\Tools\Python27\lib\site-packages\fife\fife.py", line 2158, in pump
    return _fife.Engine_pump(self)
  File "D:\Tools\Python27\lib\site-packages\fife\extensions\fife_timer.py", line 125, in updateEvent
    self._callback()
  File "D:\Tools\Python27\lib\site-packages\fife\extensions\pychan\tools.py", line 83, in real_callback
    callback(*args,**kwargs)
  File "D:\Tools\Python27\lib\site-packages\fife\extensions\pychan\events.py", line 164, in delayed_f
    f( event )
  File "D:\Tools\Python27\lib\site-packages\fife\extensions\pychan\events.py", line 327, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
  File "D:\Tools\Python27\lib\site-packages\fife\extensions\pychan\tools.py", line 60, in applyOnlySuitable
    return func(*args,**kwargs)
  File "D:\UnknownHorizons\unknown-horizons\horizons\gui\widgets\routeconfig.py", line 119, in toggle_route
    self.stop_route()
  File "D:\UnknownHorizons\unknown-horizons\horizons\gui\widgets\routeconfig.py", line 113, in stop_route
    self._route_cmd("disable")
  File "D:\UnknownHorizons\unknown-horizons\horizons\gui\widgets\routeconfig.py", line 500, in _route_cmd
    RouteConfigCommand(self.instance, method, *args, **kwargs).execute(self.session)
  File "D:\UnknownHorizons\unknown-horizons\horizons\command\__init__.py", line 47, in execute
    return session.manager.execute(self, local)
  File "D:\UnknownHorizons\unknown-horizons\horizons\manager.py", line 49, in execute
    ret = command(issuer = self.session.world.player) # actually execute the command
  File "D:\UnknownHorizons\unknown-horizons\horizons\command\__init__.py", line 72, in __call__
    return getattr(self._get_object(), self.method)(*self.args, **self.kwargs)
  File "D:\UnknownHorizons\unknown-horizons\horizons\world\traderoute.py", line 255, in disable
    self._changed()
  File "D:\UnknownHorizons\unknown-horizons\horizons\util\changelistener.py", line 106, in _changed
    self.__call_listeners(self.__listeners)
  File "D:\UnknownHorizons\unknown-horizons\horizons\util\changelistener.py", line 73, in __call_listeners
    traceback.print_stack()
Warning: the dead are listening to <horizons.world.traderoute.TradeRoute object at 0x2A56BB10> :  Instance: None Function: <function on_route_change at 0x0346A830> Function from module: horizons.gui.widgets.routeconfig
```

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/1695)
##

**Comment by squiddy** [comment] 2016-11-01 19:37
Can't reproduce it, we will see it it comes up again later. Closing in the meantime.

**Closed by squiddy** 2016-11-01 19:37 UTC
Labels: A-gui, B-bug
