### ISSUE TITLE
Game sometimes failed to exit

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2466] opened 2016-08-31 20:25 UTC
Sometimes is game unquitable. I am running it with terminal so i can terminate i iwth clicking the cross.

**Comment by LinuxDonald** [comment] 2016-08-31 20:57
Yeah i know that bug but i dont know why i happens... I have it often too when i want to close uh :(

**Comment by squiddy** [comment] 2016-10-12 18:07
I've noticed something similar, didn't really happen before. I'm using awesome WM, and when running UH from the terminal, I can interrupt it with `CTRL+C`.

However, when I use the awesome WM shortcut `CTRL+SHIFT+C` to kill the current window, it just freezes (i.e. can't move the cursor inside the game) and I'm no longer able to interrupt on the terminal.

**Comment by LinuxDonald** [comment] 2016-10-15 23:51
For me it sometimes freeze when i click on the X in window mode.

**Comment by squiddy** [comment] 2016-10-16 07:55
I'm pretty sure this is caused by locks in threads, with the preloading thread I can reproduce it. If I start the game, and shortly after seeing the menu try to end it (either by shortcut or clicking X), it will hang. `strace` reports this:

`futex(0x558d5704f400, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff`

I can get the process to hang repeatedly. If however I disable the preloading with `python run_uh.py --no-preload` this issue is not present. 

My guess is the lock isn't released when the application is instructed to close.

**Comment by squiddy** [comment] 2016-10-25 20:15
Reopened, because this still happens when inside the editor.

**Comment by LinuxDonald** [comment] 2016-10-25 20:21
I had the issue still to when uh crashes.

**Comment by squiddy** [comment] 2016-10-26 20:58
> I had the issue still to when uh crashes.

Sorry, but I don't understand what you're trying to say. You can't close the game after it crashed?

**Comment by LinuxDonald** [comment] 2016-10-27 04:09
I can't close it after it crashed. It hangs then.

**Comment by squiddy** [comment] 2016-10-27 15:35
Does this happen after every crash? And what crash exactly? So far we only
have two documented crashes.

Am 27.10.2016 12:09 vorm. schrieb "Thomas Kowaliczek" <
notifications@github.com>:

**Comment by squiddy** [comment] 2016-10-27 18:45
Interestingly enough, when I start the editor from the command line `run_uh.py --edit-map full-house` and wait until the game loaded I can exit the game just fine. If however I'm starting the editor from the main menu, exiting will hang the game.

**Closed** 2016-10-29 21:07 UTC
Labels: A-editor, B-bug
