### ISSUE TITLE
Scrolling in settings while in game scrolls the game too

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2585] opened 2016-12-25 15:27 UTC
Changing settings while in game and scrolling through menu initiate scrolling in game too. Which looks kind of bad.

**Comment by LinuxDonald** [comment] 2016-12-25 15:37
That's an know bug. I think we have already an bug report for it?

**Comment by squiddy** [comment] 2017-01-14 12:03
Duplicate of #2538 (Zooming the view continues when using mousewheel on GUI elements)

**Closed by squiddy** 2017-01-14 12:03 UTC
Labels: A-gui, B-bug
