### ISSUE TITLE
Get GUI tests working

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2636] opened 2017-03-04 09:31 UTC

**Comment by AndyMender** [comment] 2017-04-14 22:30
One of the issues thus far was that the Travis CI build virtual machine would call `coverage` in the Debian/Ubuntu way using either `python-coverage` or `python3-coverage` for Python 2.x or Python3.x, respectively. This was addressed here: a04a2d9fc6272471b0633943cfec218493a14f85

The other problem is that the Xorg dummy called Xvfb that we typically use for GUI tests has issues handling its GLX extension in the context of the GUI portion of FIFE. We therefore would need either a) means of running GUI tests without 3D acceleration provided by the GLX extension or b) find a different Xorg dummy implementation for rendering.

As I am hardly experienced in this, I would require some advice from @squiddy and @helios2000.

**Comment by LinuxDonald** [comment] 2017-04-14 23:07
When i change the render to opengl then the gui tests work. Only 2 are failing.

`[linuxdonald@linuxdonald-pc unknown-horizons]$ RUNCOV=1 python3 run_tests.py -a gui tests/gui --verbose         
Boatbuilder crashes when canceling a ship build. ... ok
Boatbuilder crashes when canceling a ship in the queue. ... ok
Boatbuilder crashes when saving/loading while a ship is being produced. ... ERROR
Boat builder running costs are inconsistent. ... ok
Boatbuilder crash with out of order finishing. ... ok
Boat builder costs don't go back to normal after cancelling a ship. ... ok
Cancelling a ship doesn't update the ship builder's tab. ... ok
Boatbuilder should not replace main production while it's paused. ... ok
tests.gui.ingame.test_bugs.test_pavilion_build_crash_built_via_settler_related_tab ... ok
Clicking on a frigate crashes the game. ... ok
Saving a game, loading it again and attempting to save it again will crash. ... ok
Selecting a warehouse from an ai player crashes. ... ok
Ship tab closed when moving away from another player's warehouse after trading. ... ok
Build related tab becomes invisible. ... ok
Clicking on a sequence of buildings may make fife throw an exception. ... ok
Crash when quickly switching between tent tabs. ... ok
Unable to select an unowned resource deposit. ... ok
Crash when completing build after outlined/related buildings were removed. ... ok
Multiselection with Ctrl crashes on many combinations. ... ok
Settlement production overview crashes if ships were produced ... ok
Triggers a crash that happens when building a storage tent on the border of the settlement ... ok
Changing language with active production overview tab crashes game ... ok
Game crashes when setting speed to zero and pressing pause twice ... ok
Game crashes when two resources are produced in the same tick and the production ... ok
Game crashes when exiting the game while the building tool is still active. ... ok
Found a settlement. ... ok
Rename a ship. ... ok
Make sure an object's name can't be changed to some empty string. ... ok
Opens chat dialog. ... ok
Test changing diplomacy status. ... ok
Build a settlement. Generated with gui logger. ... ok
Trigger different buildingtool highlights ... ok
Click on some buttons at the ingame menu. ... ok
Ship list widget (F3, formerly F4) crashes game on access. ... ok
Open the (empty) logbook. ... ok
Open the 3 three different statistic tabs in the logbook. ... ok
Select a ship. ... ok
Check group selection using ctrl-NUM ... ok                                                                                                                                                                                                                                    
Select two frigates and delete them. ... ok                                                                                                                                                                                                                                    
Check that a ship's route is configured correctly after setting it up using the GUI. ... ERROR                                                                                                                                                                                 
tests.gui.ingame.test_warehouse.test_production_overview ... ok                                                                                                                                                                                                                
Opening&closing the settings dialog in two different games crashes. ... ok                                                                                                                                                                                                     
tests.gui.ingame.test_windows.test_settings_dialog_crash2 ... ok                                                                                                                                                                                                               
Test that the credits page shows up. ... ok                                                                                                                                                                                                                                    
Test that the help page shows up. ... ok                                                                                                                                                                                                                                       
tests.gui.menu.test_mainmenu.test_settings ... ok                                                                                                                                                                                                                              
Create a game, join the lobby, change player details, send chat message. ... ok                                                                                                                                                                                                
Test refreshing of active games list. ... ok                                                                                                                                                                                                                                   
Test that the multiplayer page shows up and closes correctly. ... ok                                                                                                                                                                                                           
Test deleting a savegame. ... ok                                                                                                                                                                                                                                               
Try to delete a game, but abort when ask for confirmation. ... ok                                                                                                                                                                                                              
Test loading a game from the mainmenu. ... ok                                                                                                                                                                                                                                  
Trying to load a game with no save games available will show a popup. ... ok                                                                                                                                                                                                   
Test saving a game. ... ok                                                                                                                                                                                                                                                     
Test saving a game. ... ok                                                                                                                                                                                                                                                     
Test that the singleplayer page shows up and closes correctly. ... ok                                                                                                                                                                                                          
Test starting an existing map. ... ok                                                                                                                                                                                                                                          
Test starting a new random map. ... ok                                                                                                                                                                                                                                         
Test starting a scenario. ... ok                                                                                                                                                                                                                                               
Simple test that detects a defeat in a game. ... ok                                                                                                                                                                                                                            
Sample mission which requires multiple buildings to win. ... ok                                                                                                                                                                                                                
Simple test that detects a win in a game. ... ok                                                                                                                                                                                                                               
Test the tutorial scenario. ... ok                                                                                                                                                                                                                                             
Test that tiles are placed while dragging the mouse. ... ok                                                                                                                                                                                                                    
Place different tiles with different tile sizes. ... ok                                                                                                                                                                                                                        
Save a map in the editor. ... ok                                                                                                                                                                                                                                               
Documented example test. ... ok                                                                                                                                                                                                                                                
If a single best match can't be found, an error is raised instead. ... ok
Target widget with multiple parents and another widget with the same name, but ... ok
Target with multiple parents, select it while omitting one parent in the search ... ok
Target with multiple parents, select it without specifing the top-most widget. ... ok
If we have multiple matches for a path, return the one that fits most closely, ... ok
Target widget with multiple parents and multiple siblings. ... ok
Single widget with a child. ... ok
Single widget in the global list. ... ok
Make sure that the target is still found even if it has children itself. ... ok
A previous implementation had a bug where the code would go in a dead end when one ... ok
Test that failures in tests are detected. ... ok
Test handling of a dialog. ... ok
Test that running the game X seconds works. ... ok
Test the different ways to trigger an action in a gui. ... ok
Does nothing to see if test setup works. ... ok
Does nothing to see if the settings update works. ... ok
tests.gui.test_mousetools.test_pipette ... ok
tests.gui.test_mousetools.test_tearing ... ok
tests.gui.test_unicode.test_user_dir_contains_non_ascii ... ok

======================================================================
ERROR: Boatbuilder crashes when saving/loading while a ship is being produced.
----------------------------------------------------------------------
tests.gui.TestFailed: 

libGL: pci id for fd 5: 1002:67b0, driver radeonsi
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/radeonsi_dri.so
libGL: Using DRI3 for screen 0
Discovered old savegame file, auto-upgrading: 48 -> 76
Object 100008 of type 1 does not know when to pay its rent.
Disregard this when loading old savegames or on running cost changes.
Traceback (most recent call last):
  File "/home/linuxdonald/dev/unknown-horizons/tests/gui/__init__.py", line 210, in _tick
    cooperative.schedule()
  File "/home/linuxdonald/dev/unknown-horizons/tests/gui/cooperative.py", line 87, in schedule
    g.switch(*args, **kwargs)
  File "/home/linuxdonald/dev/unknown-horizons/tests/gui/ingame/test_boatbuilder.py", line 212, in test_save_load_ticket_1421
    saveload(gui)
  File "/home/linuxdonald/dev/unknown-horizons/tests/gui/helper.py", line 92, in saveload
    horizons.main.start_singleplayer(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 343, in start_singleplayer
    _modules.session.load(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/spsession.py", line 45, in load
    super(SPSession, self).load(*args, **kwargs)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/session.py", line 266, in load
    self.ingame_gui.load(savegame_db)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/ingamegui.py", line 346, in load
    self.logbook.load(db)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/logbook.py", line 140, in load
    self.set_cur_entry(int(value[0][0])) # this also redraws
  File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/logbook.py", line 336, in set_cur_entry
    raise ValueError
ValueError


------------------------ >> rerun the test << ------------------------
python3 run_tests.py tests.gui.ingame.test_boatbuilder:test_save_load_ticket_1421 -a gui

======================================================================
ERROR: Check that a ship's route is configured correctly after setting it up using the GUI.
----------------------------------------------------------------------
tests.gui.TestFailed: 

libGL: pci id for fd 5: 1002:67b0, driver radeonsi
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/radeonsi_dri.so
libGL: Using DRI3 for screen 0
Traceback (most recent call last):
  File "/home/linuxdonald/dev/unknown-horizons/tests/gui/__init__.py", line 210, in _tick
    cooperative.schedule()
  File "/home/linuxdonald/dev/unknown-horizons/tests/gui/cooperative.py", line 87, in schedule
    g.switch(*args, **kwargs)
  File "/home/linuxdonald/dev/unknown-horizons/tests/gui/ingame/test_traderoute.py", line 58, in test_traderoute
    gui.trigger('overview_trade_ship/configure_route')
  File "/home/linuxdonald/dev/unknown-horizons/tests/gui/helper.py", line 339, in trigger
    raise Exception("Widget '{}' not found".format(widget_name))
Exception: Widget 'overview_trade_ship/configure_route' not found


------------------------ >> rerun the test << ------------------------
python3 run_tests.py tests.gui.ingame.test_traderoute:test_traderoute -a gui

----------------------------------------------------------------------
Ran 86 tests in 1144.045s

FAILED (errors=2)
[linuxdonald@linuxdonald-pc unknown-horizons]$ 
`

**Comment by AndyMender** [comment] 2017-04-15 06:41
I can confirm that this is indeed the case. The only difference being that the name of the rendering back-end is in fact "OpenGL" as stated in the [Fifengine Developer Guide](http://docs.fifengine.net/developer-manual/en/#_engine). I'll see to it that the tests run properly on Travis CI and that the remaining tests are perhaps fixed.

**Comment by LinuxDonald** [comment] 2017-04-15 23:29
@squiddy do you maybe know what gets wrong here?

`ERROR: Check that a ship's route is configured correctly after setting it up using the GUI.
----------------------------------------------------------------------
tests.gui.TestFailed:
 
Traceback (most recent call last):
  File "/home/andy/unknown-horizons/tests/gui/__init__.py", line 210, in _tick
    cooperative.schedule()
  File "/home/andy/unknown-horizons/tests/gui/cooperative.py", line 87, in schedule
    g.switch(*args, **kwargs)
  File "/home/andy/unknown-horizons/tests/gui/ingame/test_traderoute.py", line 58, in test_traderoute
    gui.trigger('overview_trade_ship/configure_route')
  File "/home/andy/unknown-horizons/tests/gui/helper.py", line 339, in trigger
    raise Exception("Widget '{}' not found".format(widget_name))
Exception: Widget 'overview_trade_ship/configure_route' not found
 
 
------------------------ >> rerun the test << ------------------------
python3 run_tests.py tests.gui.ingame.test_traderoute:test_traderoute -a gui`

**Comment by AndyMender** [comment] 2017-04-16 07:07
I had a look at the tests/gui/helper.py and tests/gui/ingame/test_traderoute.py files and for whatever reason this test fails even if a widget used for a previous test successfully is called via `gui.trigger()`.

**Comment by squiddy** [comment] 2017-04-19 05:51
IMO it's better to disable the gui tests on Travis for now and at least fix the unit tests and code style issues. Right now the CI is completely broken and useless.

**Comment by AndyMender** [comment] 2017-04-19 08:25
Done as suggested: 8319a47737e47f1f36a0797889bcbd64f8daf4aa.

**Comment by squiddy** [comment] 2017-05-19 05:30
> On April 21st Travis CI is switching to Ubuntu 16.04 LTS, which might address this, hopefully.

I think you may have mixed things up, that date might be the release date of the LTS. As of now, Travis has no immediate plans to update, see https://github.com/travis-ci/travis-ci/issues/5821

Their suggestions is:

> You can use our Docker feature (https://docs.travis-ci.com/user/trusty-ci-environment) to pull a reasonable image and use that instead.

Which seems like something worth investigating.

**Comment by squiddy** [comment] 2017-05-20 09:49
Finally, seems like some GUI tests are running on Travis again.

branch: https://github.com/unknown-horizons/unknown-horizons/tree/travis-gui-tests
travis: https://travis-ci.org/unknown-horizons/unknown-horizons/builds/234278160?utm_source=github_status&utm_medium=notification

I've basically started from scratch before all the python3 stuff, and I think the current configuration is the same before the many changes.

@AndyMender What was the reason in changing the backend to OpenGL from SDL here https://github.com/unknown-horizons/unknown-horizons/commit/6a4f5703a4dcd30ea4cda1959b09b62fe464b8c0? Because I think that's what was causing all the problems.

**Comment by AndyMender** [comment] 2017-05-20 09:59
When I was running the tests locally then, they were failing with an SDL-related error. That's the reason I switched to OpenGL to at least be able to run the tests via X11. However, if you notice it messes up the GUI tests on Travis, we can revert it :).

**Comment by squiddy** [comment] 2017-05-20 10:08
I see. Yeah, I'm going to revert it then. We can always either fix your SDL problem or have the backend be configurable with an environment variable.

**Comment by squiddy** [comment] 2017-05-20 15:49
@AndyMender Next time you're running GUI tests and SDL is making problems, either comment here with the traceback or open up an issue. I'd prefer to solve the underlying issue.

**Comment by AndyMender** [comment] 2017-05-20 15:57
Got it and I will!

**Closed** 2017-05-20 16:08 UTC
Labels: A-internals, tests
