### ISSUE TITLE
GUI tests on CI fail without future library installed

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2704] opened 2017-06-05 07:49 UTC
I was cleaning up the requirements, and as we don't need the `future` library anymore, I removed it. But now the GUI tests are failing:

https://travis-ci.org/unknown-horizons/unknown-horizons/builds/239494227

```
________________________________ test_save_map _________________________________
fatal: No names found, cannot describe anything.
Traceback (most recent call last):
  File "run_uh.py", line 376, in <module>
    main()
  File "run_uh.py", line 114, in main
    import horizons.main
  File "/home/travis/build/unknown-horizons/unknown-horizons/horizons/main.py", line 46, in <module>
    from horizons.gui import Gui
  File "/home/travis/build/unknown-horizons/unknown-horizons/horizons/gui/__init__.py", line 22, in <module>
    from .gui import Gui
  File "/home/travis/build/unknown-horizons/unknown-horizons/horizons/gui/gui.py", line 26, in <module>
    from fife.extensions.pychan.widgets import Icon
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/fife/extensions/pychan/__init__.py", line 267, in <module>
    from .widgets import *
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/fife/extensions/pychan/widgets/__init__.py", line 33, in <module>
    from .widget import Widget
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/fife/extensions/pychan/widgets/widget.py", line 33, in <module>
    from fife.extensions.pychan import events
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/fife/extensions/pychan/events.py", line 67, in <module>
    from future.utils import itervalues
ImportError: No module named 'future'
```

I'm not sure where the problem is. Either our debian package for fife is missing this dependency, or its missing in fifengine itself. Any ideas @LinuxDonald @MasterofJOKers ?

For now, I'm going to re-add this dependency in our requirements to keep the tests running.

**Comment by LinuxDonald** [comment] 2017-06-05 11:21
As you can see in the log. It seems that pychan needs future. Have we in UH replaced future? Maybe we/Belair could do it on fife side?

**Comment by AndyMender** [comment] 2017-06-05 11:33
I think `future` was needed in the Python2 code for some Py3 features. Perhaps later, when FIFE moves completely to Python3, this will be removed. Alternatively, we could make this a conditional import in fifechan.

**Comment by LinuxDonald** [comment] 2017-06-05 11:34
When I remember correctly future lib come with port to python3.

**Comment by LinuxDonald** [comment] 2017-06-05 13:11
<Beliar> LinuxDonald, it is for the compatibility between python 2 and 3

**Comment by Beliaar** [comment] 2017-06-05 13:42
In short, it allows to use the same code in for both python 2 and 3.

**Comment by squiddy** [comment] 2017-06-05 13:49
> As you can see in the log. It seems that pychan needs future.

Well, yeah. I can see that. But just because pychan needs it, a installed fife debian package shouldn't require us to include that dependency when *we* don't need it.

**Comment by LinuxDonald** [comment] 2017-06-05 13:50
@Beliaar could you maybe change that when fife gets compiled with python3 support that it dont need future?

**Comment by squiddy** [comment] 2017-06-05 13:55
> @Beliaar could you maybe change that when fife gets compiled with python3 support that it dont need future?

The idea is to support both python 2 and 3 with the same code base. Also I feel kinda misunderstood. I don't really care whether fife needs the library or not.

I'm just saying that for CI, currently we can't use the fife package (installed system-wide) **without** installing the library separately, which feels wrong.

**Comment by Beliaar** [comment] 2017-06-05 13:55
The problem is with the extensions code, not the main module. Unless someone wants to maintain 2 versions of them it is not possible.

**Comment by MasterofJOKers** [comment] 2018-02-26 10:36
Fixed by adding a python3-future dependency to the python3-fife package and also copying what gets installed globally for python3-future to the travis user's virtualenv.

**Closed by MasterofJOKers** 2018-02-26 10:36 UTC
Labels: A-packages, B-bug, tests
