### ISSUE TITLE
Startup crash on openSUSE

### ISSUE THREAD

**Issue by iganev** [unknown-horizons/unknown-horizons#2320] opened 2015-02-26 16:20 UTC
Hello again. I have tested the game on openSUSE 13.2 (latest) and it crashes upon startup. Here is the trace:

ivan@soundreamer:~> unknown-horizons 
Discovered old settings file, auto-upgrading: 1 -> 38
Traceback (most recent call last):
  File "/usr/bin/unknown-horizons", line 380, in <module>
    main()
  File "/usr/bin/unknown-horizons", line 189, in main
    ret = horizons.main.start(options)
  File "/usr/lib/python2.7/site-packages/horizons/main.py", line 192, in start
    horizons.globals.fife.init()
  File "/usr/lib/python2.7/site-packages/horizons/engine/engine.py", line 178, in init
    self._setting.apply()
  File "/usr/lib/python2.7/site-packages/horizons/engine/settings.py", line 91, in apply
    change_language(language)
  File "/usr/lib/python2.7/site-packages/horizons/i18n/__init__.py", line 125, in change_language
    horizons.globals.fife.pychan.loadFonts(fontdef)
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/fonts.py", line 88, in loadFonts
    for font in Font.loadFromFile(filename):
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/fonts.py", line 73, in loadFromFile
    fonts.append( Font(name,_get) )
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/fonts.py", line 46, in __init__
    self.font.setAntiAlias(self.antialias)
  File "/usr/lib64/python2.7/site-packages/fife/fife.py", line 3233, in setAntiAlias
    return _fife.GuiFont_setAntiAlias(self, *args)
TypeError: in method 'GuiFont_setAntiAlias', argument 2 of type 'bool'

**Comment by stubb** [comment] 2015-02-26 17:15
Seems to be a duplicate of #2295. Fife the engine we use needs to build with Swig2.* not Swig3.*. Please inform the maintainer of the package you use!

**Comment by manuelm** [comment] 2015-03-17 00:07
swig2 has been added to our OBS repositories and I've triggered a rebuild. openSUSE 13.2 is still rebuilding, but after publishing this should be fixed.

**Comment by gryffus** [comment] 2015-04-01 00:13
The issue was fixed in games:unknown-horizons repository only. I just submitted changes to games repository and UH should be working again soon.

**Comment by gryffus** [comment] 2015-04-01 04:25
This should be marked as fixed.

**Closed** 2015-04-01 11:22 UTC
