### ISSUE TITLE
Route Config for ships is broken/crashes.

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2525] opened 2016-10-17 14:57 UTC
```pytb
[linuxdonald@linuxdonald-pc unknown-horizons]$ ./run_uh.py
The Python Imaging Library (PIL / Pillow) package is needed to run the atlas generator.
Atlas generation failed. Continuing without atlas support.
This just means that the game will run a bit slower.
It will still run fine unless there are other problems.

libGL: pci id for fd 5: 1002:67b0, driver radeonsi
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/radeonsi_dri.so
libGL: Using DRI3 for screen 0
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 173, in delayed_f
    f( event )
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 351, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable
    return func(*args,**kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/modules/pausemenu.py", line 90, in _do_quit
    self._session.quit()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/session.py", line 199, in quit
    self.end()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/session.py", line 175, in end
    self.ingame_gui = None # keep this before world
 File "/home/linuxdonald/dev/unknown-horizons/horizons/util/living.py", line 63, in __set__
    self.__value.end()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/ingamegui.py", line 192, in end
    self.hide_menu()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/ingamegui.py", line 312, in hide_menu
    self.show_menu(None)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/ingamegui.py", line 300, in show_menu
    self._old_menu.hide()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 152, in hide
    self.current_tab.hide()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/tabs/shiptabs.py", line 129, in hide
    self.route_menu.hide()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/routeconfig.py", line 93, in hide
    self.session.ingame_gui.message_widget.add('ROUTE_DISABLED')
AttributeError: 'NoneType' object has no attribute 'add'

Traceback (most recent call last):
  File "./run_uh.py", line 382, in <module>
    main()
  File "./run_uh.py", line 191, in main
    ret = horizons.main.start(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 281, in start
    horizons.globals.fife.run()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 278, in run
    self.loop()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 285, in loop
    self.engine.pump()
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 2716, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not closed
[linuxdonald@linuxdonald-pc unknown-horizons]$ 

```

**Comment by LinuxDonald** [comment] 2016-10-17 14:58
And when i want to load that savegame where i have added an route config i become this crash: `[linuxdonald@linuxdonald-pc unknown-horizons]$ ./run_uh.py
The Python Imaging Library (PIL / Pillow) package is needed to run the atlas generator.
Atlas generation failed. Continuing without atlas support.
This just means that the game will run a bit slower.
It will still run fine unless there are other problems.

libGL: pci id for fd 5: 1002:67b0, driver radeonsi
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/radeonsi_dri.so
libGL: Using DRI3 for screen 0
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 173, in delayed_f
    f( event )
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 351, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable
    return func(*args,**kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/util/python/callback.py", line 47, in __call__
    return self.callback(*self.args, **self.kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/tabs/shiptabs.py", line 51, in _configure_route
    self._windows.toggle(self.route_menu)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/windows.py", line 338, in toggle
    self.open(window, **kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/windows.py", line 314, in open
    return window.open(**kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/windows.py", line 53, in open
    return self.show(**kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/routeconfig.py", line 73, in show
    self.minimap.draw()
AttributeError: 'RouteConfig' object has no attribute 'minimap'

Traceback (most recent call last):
  File "./run_uh.py", line 382, in <module>
    main()
  File "./run_uh.py", line 191, in main
    ret = horizons.main.start(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 281, in start
    horizons.globals.fife.run()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 278, in run
    self.loop()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 285, in loop
    self.engine.pump()
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 2716, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not closed
[linuxdonald@linuxdonald-pc unknown-horizons]$ 
`

**Comment by LinuxDonald** [comment] 2016-10-17 14:59
Savegame file
[test-crash.sqlite.zip](https://github.com/unknown-horizons/unknown-horizons/files/533816/test-crash.sqlite.zip)

**Comment by MasterofJOKers** [comment] 2016-10-17 15:09
Cannot reproduce with the save-game and `./run_uh.py --load-game test-crash`.

**Comment by MasterofJOKers** [comment] 2016-10-17 15:38
@squiddy After using `git bisect`, b23f3468deb2c6f4c9b66cecd9a8959b141a9bee introduced the crash. Can you please have a look at it?

**Comment by squiddy** [comment] 2016-10-17 21:42
Some information on how to reproduce the bug, or at least, which actions led to the crash, would be really helpful.

**Comment by MasterofJOKers** [comment] 2016-10-17 21:48
Oh, `./run_uh.py --load-game test-crash` then click on the route menu symbol of the ship.

**Comment by squiddy** [comment] 2016-10-17 21:49
The likely issue here is that when ending the game, `Session` does `self.ingame_gui = None`, which, besides setting that attribute to None (d'oh), also invokes the LivingObject magic that will call end on the old object. If any code during this function call accesses session.ingame_gui it will break, since it was already set to None.

I guess we could fix that by invoking end explicitly, and then setting the reference to None.

```python
if self.ingame_gui:
    self.ingame_gui.end()
self.ingame_gui = None
```

Still, something to reproduce would be nice.

**Comment by squiddy** [comment] 2016-10-17 21:50
@MasterofJOKers So the steps that lead to the crash are not known? I don't like having only a savegame to reproduce it, simple steps make it easier to write a test.

**Comment by MasterofJOKers** [comment] 2016-10-17 21:51
Well, there are two crashes here. The one when loading the savegame is reproduced as above. The over one seems to be: create a trading route.

**Comment by MasterofJOKers** [comment] 2016-10-17 21:58
Sorry, you're right. Creating a trading route works. @LinuxDonald You should write better tickets! Just creating  trading route works flawlessly for me.

**Comment by LinuxDonald** [comment] 2016-10-18 01:59
The first crash: create an route add for example lumber to it don't start the route save the game. Than close the game it should crash.

Second crash: load the created savegame open the route config

**Comment by squiddy** [comment] 2016-10-20 15:46
You don't even have to save the game to trigger the crash, all it takes is to have the route config open when closing the game.

**Comment by LinuxDonald** [comment] 2016-10-20 16:39
The pr fix the first problem but not the second when you want to load the saved game and open route config it crashes.

```
[linuxdonald@linuxdonald-pc unknown-horizons]$ ./run_uh.py
The Python Imaging Library (PIL / Pillow) package is needed to run the atlas generator.
Atlas generation failed. Continuing without atlas support.
This just means that the game will run a bit slower.
It will still run fine unless there are other problems.

libGL: pci id for fd 5: 1002:67b0, driver radeonsi
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/radeonsi_dri.so
libGL: Using DRI3 for screen 0
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 173, in delayed_f
    f( event )
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 351, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable
    return func(*args,**kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/util/python/callback.py", line 47, in __call__
    return self.callback(*self.args, **self.kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/tabs/shiptabs.py", line 51, in _configure_route
    self._windows.toggle(self.route_menu)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/windows.py", line 338, in toggle
    self.open(window, **kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/windows.py", line 314, in open
    return window.open(**kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/windows.py", line 53, in open
    return self.show(**kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/routeconfig.py", line 73, in show
    self.minimap.draw()
AttributeError: 'RouteConfig' object has no attribute 'minimap'

Traceback (most recent call last):
  File "./run_uh.py", line 382, in <module>
    main()
  File "./run_uh.py", line 191, in main
    ret = horizons.main.start(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 286, in start
    horizons.globals.fife.run()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 278, in run
    self.loop()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/engine/engine.py", line 285, in loop
    self.engine.pump()
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 2716, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not closed
[linuxdonald@linuxdonald-pc unknown-horizons]$
```

**Comment by squiddy** [comment] 2016-10-20 16:48
Ah yes, my bad. Forgot about the second traceback. :)

**Comment by squiddy** [comment] 2016-10-22 08:38
@LinuxDonald I've updated the PR with a fix for the other crash.

**Closed** 2016-10-22 16:42 UTC
Labels: A-gui, B-crash
