### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by Jeeppler** [unknown-horizons/unknown-horizons#2396] opened 2016-06-26 00:38 UTC
the latest release is [2014.1](http://www.unknown-horizons.org/devblog/113/114/Unknown-Horizons-Release-2014-1/). It is over two years old. 

Many new features have been developed, since 2014. None of the new features can be used by players who are not familiar with git and compiling stuff.

**Comment by LinuxDonald** [comment] 2016-06-26 00:44
We have some open bugs that must be fixed before can do an new releases.
See https://github.com/unknown-horizons/unknown-horizons/milestones/2016.1

I hoped we can do an released in the next months but we need Python coders.

**Comment by Jeeppler** [comment] 2016-06-26 01:01
@LinuxDonald who is managing the community around UH right now?

**Comment by LinuxDonald** [comment] 2016-06-26 01:02
That's my job :-)

**Comment by Jeeppler** [comment] 2016-06-26 01:12
Is there any simple task which could be done to make a 2016 release possible?

**Comment by LinuxDonald** [comment] 2016-06-26 01:28
Maybe this one: https://github.com/unknown-horizons/unknown-horizons/issues/2373

But you're can look on the bugtracker for other issues for starting to code on UH.

**Comment by LinuxDonald** [comment] 2016-06-26 01:32
I will writer laters an list with issues that's are maybe easy to fix.

**Comment by Jeeppler** [comment] 2016-06-26 10:07
@LinuxDonald it would be better to use the tags: `simple` and `help wanted` as well as assign a priority or milestone to each of them. A tag makes it easy to find the issues.

**Comment by LinuxDonald** [comment] 2016-06-26 10:20
https://github.com/unknown-horizons/unknown-horizons/labels/starter

**Comment by Jeeppler** [comment] 2016-06-26 10:26
should be mentioned in this guide: https://github.com/unknown-horizons/unknown-horizons/wiki/Getting-started

The link under ["Hacking the Code"](http://www.unknown-horizons.org/get-involved/) leads to a dead page: http://wiki.unknown-horizons.org/w/Programmers_Guide

**Comment by LinuxDonald** [comment] 2016-06-26 10:34
Where you have found the dead link? I can't find it. The wiki page that your linked is the old one. Now we use github wiki. But I will add laters the starters tickets link to the wiki.

**Comment by Jeeppler** [comment] 2016-06-26 10:36
You can find Hacking the Code here http://www.unknown-horizons.org/get-involved/

**Comment by LinuxDonald** [comment] 2016-06-26 10:54
The programmer guide link is working for me. It links to github wiki.

**Comment by Jeeppler** [comment] 2016-06-26 10:56
You can also click on the image, besides "Hacking the Code", that is the dead link. Sorry for the confusion.

**Comment by LinuxDonald** [comment] 2016-06-26 11:00
@stubb have you access to it? Can you fix that?

**Comment by stubb** [comment] 2016-06-27 16:39
@Jeeppler Fixed it!

**Comment by LinuxDonald** [comment] 2016-08-22 09:02
New release is planned this year. We are talk now with the fife devs about an new fife and fifechan release.

**Comment by LinuxDonald** [comment] 2016-08-25 05:38
Update on Engine side: The fife Team is nearing to be done with an new SDK for Windows. When this is done we are forward an first step for an new release.

**Comment by Jeeppler** [comment] 2016-08-25 21:38
That sounds great :-)

**Comment by LinuxDonald** [comment] 2016-12-11 02:20
https://github.com/fifengine/fife-windows-sdk/issues/6

**Comment by Jeeppler** [comment] 2016-12-15 14:28
@LinuxDonald are you still considering to release a new UH version for this year?

**Comment by LinuxDonald** [comment] 2016-12-15 14:32
I hope it really. We are still working on it. We have two problems at the moment. One is the fife Windows SDK and after that UH windows installer. And we have fixed an bug/problem in the fife swig/python interface for that uh now need an fix/change too. After the fife change is fixed in UH we could release the new version of uh but only for Linux. And engine too only for Linux.

**Comment by Jeeppler** [comment] 2016-12-15 14:46
It seems like you did a lot of progress over the past months. If you can not make it this year. Make a 2017 New Year edition :-)

**Comment by LinuxDonald** [comment] 2016-12-21 16:04
Sorry but we can not do an release this year sorry for this. New release is planned for Q1 2017.

**Comment by Jeeppler** [comment] 2016-12-22 15:36
I hope you will make it for 2017. Keep me updated :-)

**Comment by LinuxDonald** [comment] 2017-01-10 17:48
Windows installer is done. Its not perfect but it works :)

**Comment by Jeeppler** [comment] 2017-01-10 18:46
Nice, that means one step closer to a new release :-)

**Comment by LinuxDonald** [comment] 2017-01-16 17:37
Done :)

**Closed by LinuxDonald** 2017-01-16 17:37 UTC

**Comment by adrian5** [comment] 2017-07-28 08:38
I wanted to give this game another try (always crashed last time), but from what I can see, Linux users need to build FIFE themselves, which is a fairly involved process. I assume Windows users get the _download, install and play_ experience? Otherwise what's the point of maintaining a game that only a small circle of developers will play.

**Comment by LinuxDonald** [comment] 2017-07-28 13:14
On Linux is is the "Job" of the package Maintainers to update the Distro Linux Packages and not really our job. And we are really an small Team :( Sorry that your distro dont provide an package?

**Comment by AndyMender** [comment] 2017-07-28 21:12
@adrian5, in theory we could provide UH packages for all/most mainstream distributions, for instance via the SUSE Open Build System. The problem is that our game requires the external FIFE and fifechan engine libraries, which are outside of our (at least my) jurisdiction.

**Comment by adrian5** [comment] 2017-07-28 21:23
> On Linux is is the "Job" of the package Maintainers to update the Distro Linux Packages and not really our job. And we are really an small Team :( Sorry that your distro dont provide an package?

But isn't that odd, to provide the game without the necessary libraries? I've never had to build a game myself, unless I wanted to test a development version. I understand though if it's too much work, that's unfortunate.

> The problem is that our game requires the external FIFE and fifechan engine libraries, which are outside of our (at least my) jurisdiction.

Hmm, I see. Is baking them into the application if out of the question? These days, there are self-contained formats like AppImage, Flatpak, Snap which could serve all Linux users (at least the 95% running x86_64).

**Comment by AndyMender** [comment] 2017-07-29 18:44
A long time ago there were multiple game projects relying on the FIFE engine. New ones might appear in the future. It is possible to bundle FIFE and fifechan with Unknown Horizons, though it is my belief that it's better to retain modularity and package them separately. Also, currently FIFE supports both Python 2 and Python 3, while our primary interest is Python 3.

**Comment by LinuxDonald** [comment] 2017-07-29 18:58
In the future it will maybe provide ubuntu packages. Because I switched over to ubuntu.
