### ISSUE TITLE
ImportError: No module named 'fife'

### ISSUE THREAD

**Issue by UHwan** [unknown-horizons/unknown-horizons#2761] opened 2017-12-06 19:35 UTC
Hello, can someone explain this to me? I have installed fifengine and tried again but still didn't work.

~/unknown-horizons $ ./run_uh.py

Traceback (most recent call last):
  File "./run_uh.py", line 385, in <module>
    main()
  File "./run_uh.py", line 114, in main
    import horizons.main
  File "/home/---/unknown-horizons/horizons/main.py", line 41, in <module>
    from fife import fife as fife_module
ImportError: No module named 'fife'

I have python 2 and python 3, so maybe this is the problem and its just try to do something with both pythons at the same time? Just write what commands I have to write in Terminal or something since I don't know them - noob with Linux, thx in advance.

**Comment by LinuxDonald** [comment] 2017-12-06 22:40
What version of uh and fife?

**Comment by UHwan** [comment] 2017-12-12 16:14
I just installed it, so it has to be the latest I assume.

**Comment by LinuxDonald** [comment] 2017-12-12 16:23
How you have installed it?

**Comment by UHwan** [comment] 2017-12-12 18:32
https://github.com/unknown-horizons/unknown-horizons/wiki/Linux

Installing Unknown-Horizons from source

    First step get git version:

git clone git://github.com/unknown-horizons/unknown-horizons.git

    Second step build the translations:

cd unknown-horizons && ./setup.py build_i18n

    Now you can run Unknown-Horizons with:

./run_uh.py   <- and when I input this line it says what I have posted first.

**Comment by LinuxDonald** [comment] 2017-12-13 04:02
And how you have installed fifechan and fife?

**Comment by UHwan** [comment] 2017-12-13 18:32
https://github.com/fifengine/fifengine
https://github.com/fifengine/fifechan and I downloaded it through git clone

**Comment by Chickengames** [comment] 2017-12-15 17:23
Stop!!!😡😤

**Comment by LinuxDonald** [comment] 2017-12-15 17:41
Have you compiled it with python3 support?

-DPYTHON_EXECUTABLE=PATH-TO-PYTHON3

**Comment by UHwan** [comment] 2017-12-15 19:45
No I didn't. I have found this location https://ubuntuforums.org/showthread.php?t=1906067 : /usr/bin/env to change it but still don;t know how to access that. I have changed in fifengine: setup.py  #!/usr/bin/env python  <- this line to this: #!/usr/bin/env python3 and it still didn't worked, In unknown horizons folder in setup.py it was already this: #!/usr/bin/env python3. If you want just tell me where to input this line: -DPYTHON_EXECUTABLE=PATH-TO-PYTHON3. I tried to open folder with python but its just nowhere to find and as I told before I am noob at this so bare with me ;d

**Comment by LinuxDonald** [comment] 2017-12-16 11:04
mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DPYTHON_EXECUTABLE=/usr/bin/python3 ..

**Comment by UHwan** [comment] 2017-12-16 19:53
mkdir_build; cd_build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr

mkdir_build: command not found
No command 'cd_build' found, did you mean:
 Command 'nd_build' from package 'neurodebian-dev' (universe)
cd_build: command not found
The program 'cmake' is currently not installed. You can install it by typing:
sudo apt install cmake

**Comment by LinuxDonald** [comment] 2017-12-16 20:02
You have copyed wrong the command please use copy and paste...

mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DPYTHON_EXECUTABLE=/usr/bin/python3

**Comment by UHwan** [comment] 2017-12-17 16:24
mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DPYTHON_EXECUTABLE=/usr/bin/python3
CMake Error: The source directory "/home/.../_build/_build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.


sudo apt install cmake
[sudo] password for ...: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version (3.5.1-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by LinuxDonald** [comment] 2017-12-17 17:35
Upps my copy paste error Sorry:

mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DPYTHON_EXECUTABLE=/usr/bin/python3 ..

Forgot the .. at the end

**Comment by UHwan** [comment] 2017-12-17 18:40
mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
CMake Error: The source directory "/home/.../_build/_build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

still can't find CMakeList.txt. despite the fact that it is installed

**Comment by LinuxDonald** [comment] 2017-12-17 18:44
i see the problem you are in the wrong folder. Delete the _build folder in your fifengine folder and excute the command again.

**Comment by UHwan** [comment] 2017-12-17 18:53
In fifengine I have only "build" folder not "_build" and in that folder Its another one: "appveyor" and in that folder its this: copy-boost-to-includes.bat and it contains this:

@echo off

echo "=== Copy the pre-installed Boost to the includes folder"

:: create folders
mkdir C:\projects\fifengine-dependencies\includes\lib\boost
mkdir C:\projects\fifengine-dependencies\includes\include\boost

:: copy boost includes
xcopy /Y /S "C:\Libraries\boost_1_63_0\boost" "C:\projects\fifengine-dependencies\includes\include\boost" >nul 2>&1

:: copy binaries (dlls) and libs
copy "C:\Libraries\boost_1_63_0\lib32-msvc-14.0\boost_filesystem-vc140-mt-1_63.dll" "C:\projects\fifengine-dependencies\includes\bin\boost_filesystem-vc140-mt-1_63.dll"
copy "C:\Libraries\boost_1_63_0\lib32-msvc-14.0\boost_system-vc140-mt-1_63.dll" "C:\projects\fifengine-dependencies\includes\bin\boost_system-vc140-mt-1_63.dll"
copy "C:\Libraries\boost_1_63_0\lib32-msvc-14.0\libboost_filesystem-vc140-mt-1_63.lib" "C:\projects\fifengine-dependencies\includes\lib\boost\libboost_filesystem-vc140-mt-1_63.lib"
copy "C:\Libraries\boost_1_63_0\lib32-msvc-14.0\libboost_system-vc140-mt-1_63.lib" "C:\projects\fifengine-dependencies\includes\lib\boost\libboost_system-vc140-mt-1_63.lib"

:: remove the "share" folder
rmdir /S /Q C:\projects\fifengine-dependencies\includes\share

echo "Done."

I have deleted "_build" folder in /home/username/ and this is what terminal is telling to me now:

mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
mkdir: cannot create directory ‘_build’: No such file or directory
bash: cd: _build: No such file or directory
Current working directory cannot be established.

**Comment by LinuxDonald** [comment] 2017-12-17 19:46
You must excute the command in the fifengine folder

**Comment by UHwan** [comment] 2017-12-17 21:34
mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /home/.../fifengine/_build/CMakeFiles/CMakeTmp


  Run Build Command:"/usr/bin/make" "cmTC_874e9/fast"

  /usr/bin/make -f CMakeFiles/cmTC_874e9.dir/build.make
  CMakeFiles/cmTC_874e9.dir/build

  make[1]: Entering directory
  '/home/.../fifengine/_build/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_874e9.dir/testCCompiler.c.o

  /usr/bin/cc -o CMakeFiles/cmTC_874e9.dir/testCCompiler.c.o -c
  /home/.../fifengine/_build/CMakeFiles/CMakeTmp/testCCompiler.c

  Linking C executable cmTC_874e9

  /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_874e9.dir/link.txt
  --verbose=1

  /usr/bin/cc CMakeFiles/cmTC_874e9.dir/testCCompiler.c.o -o cmTC_874e9
  -rdynamic

  /usr/bin/ld: cannot find crt1.o: No such file or directory

  /usr/bin/ld: cannot find crti.o: No such file or directory

  /usr/bin/ld: cannot find -lc

  /usr/bin/ld: cannot find crtn.o: No such file or directory

  collect2: error: ld returned 1 exit status

  CMakeFiles/cmTC_874e9.dir/build.make:97: recipe for target 'cmTC_874e9'
  failed

  make[1]: *** [cmTC_874e9] Error 1

  make[1]: Leaving directory '/home/.../fifengine/_build/CMakeFiles/CMakeTmp'

  Makefile:126: recipe for target 'cmTC_874e9/fast' failed

  make: *** [cmTC_874e9/fast] Error 2


  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


CMake Error at CMakeLists.txt:7 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/.../fifengine/_build/CMakeFiles/CMakeOutput.log".
See also "/home/.../fifengine/_build/CMakeFiles/CMakeError.log

__________________________________________________________________
Here is CMakeOutput.log:

The system is: Linux - 4.10.0-42-generic - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc 
Build flags: 
Id flags: -c

The output was:
0


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"

The C compiler identification is GNU, found in "/home/.../fifengine/_build/CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.o"

__________________________________________________________________________
Here is CMakeError.log:

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: 
Id flags: 

The output was:
1
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags: 

The output was:
No such file or directory


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags: -c

The output was:
No such file or directory


Determining if the C compiler works failed with the following output:
Change Dir: /home/.../fifengine/_build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_874e9/fast"
/usr/bin/make -f CMakeFiles/cmTC_874e9.dir/build.make CMakeFiles/cmTC_874e9.dir/build
make[1]: Entering directory '/home/.../fifengine/_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_874e9.dir/testCCompiler.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_874e9.dir/testCCompiler.c.o   -c /home/.../fifengine/_build/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_874e9
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_874e9.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_874e9.dir/testCCompiler.c.o  -o cmTC_874e9 -rdynamic 
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_874e9.dir/build.make:97: recipe for target 'cmTC_874e9' failed
make[1]: *** [cmTC_874e9] Error 1
make[1]: Leaving directory '/home/.../fifengine/_build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_874e9/fast' failed
make: *** [cmTC_874e9/fast] Error 2
_______________________________________________________________________________
So, it's like I should download C#/C++ compiler, whatever that is?

**Comment by LinuxDonald** [comment] 2017-12-17 23:36
Do an sudo apt-get install gcc

**Comment by UHwan** [comment] 2017-12-17 23:37
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by LinuxDonald** [comment] 2017-12-19 06:00
Maybe try install sudo apt-get install libc6-dev

It seems there is something broken with your linux.

**Comment by Chickengames** [comment] 2017-12-19 15:05
I don’t care I’m report you on github.io about email spam this is the 17 email. STOP!

**Comment by UHwan** [comment] 2017-12-22 16:10
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:7 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/aio/fifengine/_build/CMakeFiles/CMakeOutput.log".
See also "/home/aio/fifengine/_build/CmakeFiles/CMakeError.log".

https://stackoverflow.com/questions/9699930/cmake-complains-the-cxx-compiler-identification-is-unknown

sudo apt-get install build-essential

update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode


CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2.cmake:168 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:751 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/aio/fifengine/_build/CMakeFiles/CMakeOutput.log".
See also "/home/aio/fifengine/_build/CmakeFiles/CmakeError.log".
https://wiki.libsdl.org/Installation#Linux.2FUnix
sudo apt-get install libsdl2-2.0     already was installed
sudo apt-get install libsdl2-dev    and after that it changed to “not found SDL2_image”

-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES
  SDL2_IMAGE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2_image.cmake:91 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:752 (find_package)


-- Configuring incomplete, errors occurred!
http://lazyfoo.net/tutorials/SDL/06_extension_libraries_and_loading_other_image_formats/linux/index.php
apt-cache search libsdl2-image
--------------------------------------------------------
sudo apt-get install libsdl2-image-2.0-0
libsdl2-image-2.0-0 is already the newest version (2.0.1+dfsg-2).
libsdl2-image-2.0-0 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sudo apt-get install libsdl2-image-dbg  but still the output was:

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES
  SDL2_IMAGE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
sudo apt-get install libsdl2-image-dev  

The following NEW packages will be installed:
  libsdl2-image-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.

Than:

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SDL2_ttf (missing: SDL2_TTF_LIBRARIES SDL2_TTF_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2_ttf.cmake:91 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:753 (find_package)
apt-cache search libsdl2-ttf
--------------------------------------------------------
sudo apt-get install libsdl2-ttf-2.0-0

libsdl2-ttf-2.0-0 is already the newest version (2.0.14+dfsg1-1).
libsdl2-ttf-2.0-0 set to manually installed.
--------------------------------------------------------
sudo apt-get install libsdl2-ttf-dbg

The following NEW packages will be installed:
  libsdl2-ttf-dbg
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
--------------------------------------------------------
sudo apt-get install libsdl2-ttf-dev

The following NEW packages will be installed:
  libsdl2-ttf-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
--------------------------------------------------------
After that:

-- Could NOT find Boost
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindPNG.cmake:157 (find_package_handle_standard_args)
  CMakeLists.txt:755 (find_package)

And I have installed mixer – just in case:

apt-chache search libsdl2-mixer
--------------------------------------------------------
sudo apt-get install libsdl2-mixer-2.0-0

libsdl2-mixer-2.0-0 is already the newest version (2.0.1+dfsg1-1).
libsdl2-mixer-2.0-0 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--------------------------------------------------------
sudo apt-get install libsdl2-mixer-dbg

The following NEW packages will be installed:
  libsdl2-mixer-dbg
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
--------------------------------------------------------
sudo apt-get install libsdl2-mixer-dev

The following NEW packages will be installed:
  libsdl2-mixer-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
--------------------------------------------------------
http://www.libpng.org/pub/png/libpng.html
https://libpng.sourceforge.io/index.html

apt-cache search libpng

sudo apt-get install libpng16-16

The following NEW packages will be installed:
  libpng16-16
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
--------------------------------------------------------
sudo apt-get install libpng16-dev

The following additional packages will be installed:
  libpng16-devtools
Recommended packages:
  libpng16-tools
The following NEW packages will be installed:
  libpng16-dev libpng16-devtools
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
--------------------------------------------------------
sudo apt-get install libpng16-tools

The following NEW packages will be installed:
  libpng16-tools
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.

From now its just a freaking JOKE and it is hilarious and I don’t even want to play this game anymore, its just to funny to stop now :D

-- Could NOT find Boost
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.20") 
-- Could NOT find OPENALSOFT (missing:  OPENALSOFT_LIBRARY OPENALSOFT_INCLUDE_DIR) 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find TinyXML (missing: TinyXML_LIBRARY TinyXML_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTinyXML.cmake:95 (find_package_handle_standard_args)
  CMakeLists.txt:757 (find_package)

I have downloaded Boost:
http://www.boost.org/users/download/
http://www.boost.org/doc/libs/1_66_0/more/getting_started/unix-variants.html
I've extracted it into /home/.../Boost, it didn't worked out so I even copied it into fifengine folder but that didn't work either and it says that I don't have to install it, its like just extract it. I can also download it by one from this commend: apt-cache search boost but its just so many different Libraries that installing all of the by hand is just to ridiculous.

**Comment by LinuxDonald** [comment] 2017-12-22 20:26
Try this: sudo apt-get install -y build-essential libalsa-ocaml-dev libsdl2-dev libboost-dev libsdl2-ttf-dev libsdl2-image-dev libvorbis-dev libalut-dev python3 python3-dev libboost-regex-dev libboost-filesystem-dev libboost-test-dev swig zlib1g-dev libopenal-dev git python3-yaml libxcursor1 libxcursor-dev cmake cmake-data libtinyxml-dev libpng-dev libglew-dev

**Comment by nihathrael** [comment] 2018-01-21 19:34
@UHwan Did you manage to get fife compiled and working with Unknown Horizons? If so, can we close this ticket?

**Comment by UHwan** [comment] 2018-02-21 13:40
Actually no, I just had no time to make it work and I am telling you that someone just don't want me to play this game ;d

-- Found the following FifeChan libraries:
--   fifechan_sdl not found.
-- Could NOT find FIFECHAN (missing:  FIFECHAN_LIBRARY FIFECHAN_INCLUDE_DIR) 
-- Found the following FifeChan libraries:
--   fifechan_opengl not found.
-- Could NOT find FIFECHAN (missing:  FIFECHAN_LIBRARY FIFECHAN_INCLUDE_DIR) 
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.8") 
CMake Error at CMakeLists.txt:865 (message):
  You are using SWIG v3.0.8.

                           This version doesn't work with fifengine.
   
                           Please upgrade SWIG.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FIFECHAN_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/.../fifengine
   used as include directory in directory /home/.../fifengine
   used as include directory in directory /home/.../fifengine
   used as include directory in directory /home/.../fifengine
__________________________________________________
So I deleted both folders of fifechan and fifengine and installed it again from this source:
[http://docs.fifengine.net/developer-manual/en/#_building_fifengine_on_linux](url)
but than:
Could not locate CEGUI, so I wanted to install it from this site:
[http://cegui.org.uk/wiki/CEED](url) and:

[ 27%] Linking CXX shared library ../../../../lib/libCEGUIOpenGLRenderer-0.so
[ 27%] Built target CEGUIOpenGLRenderer-0
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
____________________________________________
You know what, I wanted to play this game for a little while, its not like I need it to live and I don't have time to just spend it on trying to make it work but I am really thankful for all help I've got on this site and yes, You can close this topic.

**Comment by LinuxDonald** [comment] 2018-02-22 07:54
First problem fifechan is not correctly installed. Second problem swig 3.0.8 dont work with fife because it have but you need 3.0.7 or 3.0.9+.
To disable cegui support just add an: -Dcegui=OFF

for example: 
in fife folder:
mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr  -Dcegui=OFF DPYTHON_EXECUTABLE=/usr/bin/python3 ..

**Comment by LinuxDonald** [comment] 2018-07-20 18:11
Any news here?

**Comment by Rootyjr** [comment] 2018-07-29 13:06
You need to install libsdl or whatever package provides SDL1.2. After that try rebuilding fifechan and fifengine. I had the same problem when I tried building fifechan & fifengine.

**Comment by LinuxDonald** [comment] 2018-07-29 15:49
Fife require sdl2

**Comment by Rootyjr** [comment] 2018-07-29 15:55
I'm not certain but I think it requires both. I have no evidence to support this fact except that the errors say they found SDL2 and its looking for SDL and that when I personally encountered this problem I installed SDL and it started working.

**Comment by Rootyjr** [comment] 2018-07-29 17:06
Here are several settings in CMakeLists.txt:

OPTION(ENABLE_SDL "Enable the Fifechan SDL extension"                                                ON)
OPTION(ENABLE_SDL_CONTRIB "Enable the Fifechan SDL contrib extension (SDL2_ttf)" OFF)
OPTION(BUILD_FIFECHAN_SDL_SHARED "Build the Fifechan SDL extension library as a shared library"                                                                                                                                      ON)

**Comment by LinuxDonald** [comment] 2018-07-29 17:30
Yeah all SDL2

**Comment by LinuxDonald** [comment] 2018-07-29 17:31
Maybe if you compile with cegui support. I dont know what cegui all require.

**Comment by LinuxDonald** [comment] 2018-07-29 17:34
For Ubuntu/debian based distros:

> apt-get install -y build-essential libalsa-ocaml-dev libsdl2-dev libboost-dev libsdl2-ttf-dev libsdl2-image-dev libvorbis-dev libalut-dev python3 python3-dev libboost-regex-dev libboost-filesystem-dev libboost-test-dev swig zlib1g-dev libopenal-dev git python3-yaml libxcursor1 libxcursor-dev cmake cmake-data libtinyxml-dev libpng-dev libglew-dev

http://docs.fifengine.net/developer-manual/en/#_building_fifengine_on_linux

**Comment by Rootyjr** [comment] 2018-07-29 18:58
I see stuff about SDL2_IMAGE, SDL2_LIBRARY, etc. What's interesting is there is one library it looks for that doesn't have a 2 on it: SDL_TTF_LIBRARY. That being said I found this in the win32 section so it may not apply to linux. But that is the best evidence I have found so far.

**Comment by Rootyjr** [comment] 2018-07-29 19:03
I'll try rebuilding it and let you know.

**Comment by Rootyjr** [comment] 2018-07-30 00:01
Well I tested and you were right. It doesn't seem to depend on SDL which is odd because last time I installed it all my problems went away. I have no clue what the cause of this issue is.

**Comment by LinuxDonald** [comment] 2018-09-13 17:18
Closed because of no new updates from the issue creator.

**Closed by LinuxDonald** 2018-09-13 17:18 UTC
